name: test
on:
  - push
  - pull_request
jobs:
  test:
    name: Node.js ${{ matrix.node-version }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node-version:
          - 16
        os:
          - windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies (Ubuntu)
        if: runner.os == 'Linux'
        run: sudo apt-get install nasm cmake libpng-dev
      - name: Install dependencies (macOS)
        if: runner.os == 'macOS'
        run: brew install cmake nasm libpng zlib
      - name: Install dependencies (Windows)
        if: runner.os == 'Windows'
        uses: msys2/setup-msys2@v2
        with:
          update: true
          install: zlib nasm libpng cmake
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm test
